library(gamlss)
data(iris)
m <- gamlss(Sepal.Length ~ random(Species), data = iris)
cat("=== names(m) ===\n")
print(names(m))
cat("\n=== coef(m) ===\n")
print(coef(m))
cat("\n=== fitted(m) by Species ===\n")
tapply(fitted(m), iris$Species, mean)
cat("\n=== try getSlope ===\n")
tryCatch({
  print(getSlope(m))
}, error = function(e) cat("getSlope failed:", e$message, "\n"))
cat("\n=== try ranef via re() ===\n")
m2 <- gamlss(Sepal.Length ~ re(factor(Species)), data = iris)
tryCatch({
  print(ranef(m2))
}, error = function(e) cat("ranef(m2) failed:", e$message, "\n"))
cat("\n=== coef(m2) ===\n")
print(coef(m2))
